# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name          = "devise_metamask"
  spec.version       = DeviseMetamask::VERSION
  spec.authors       = ["Your Name"]
  spec.email         = ["you@example.com"]

  spec.summary       = "Add MetaMask login support to Devise-enabled Rails apps"
  spec.description   = <<~DESC
    DeviseMetamask provides a custom Warden strategy for signing into a Ruby on
    Rails application with an Ethereum address via MetaMask.  It verifies
    signatures generated by the browser extension and associates them with a
    user model, rotating nonces to prevent replay attacks.  This gem is a
    starting point for applications that want to authenticate users using
    blockchain accounts instead of passwords.
  DESC
  spec.homepage      = "https://github.com/your-name/devise_metamask"
  spec.license       = "MIT"

  spec.files         = Dir.chdir(File.expand_path(__dir__)) do
    Dir['lib/**/*', 'README.md', 'LICENSE.txt']
  end

  spec.required_ruby_version = '>= 2.7'

  # Devise is required for authentication and Warden integration
  spec.add_runtime_dependency 'devise', '>= 4.7'
  # The eth gem provides methods to recover Ethereum addresses from signatures
  spec.add_runtime_dependency 'eth', '>= 0.5'

  spec.metadata['rubygems_mfa_required'] = 'true'
end